export const accountTypes = {
  ACCOUNT_HISTORY_REQUEST: "ACCOUNT_HISTORY_REQUEST",
  ACCOUNT_HISTORY_SUCCESS: "ACCOUNT_HISTORY_SUCCESS",
  ACCOUNT_HISTORY_FAILURE: "ACCOUNT_HISTORY_FAILURE",

  SEND_COIN_REQUEST: "SEND_COIN_REQUEST",
  SEND_COIN_SUCCESS: "SEND_COIN_SUCCESS",
  SEND_COIN_FAILURE: "SEND_COIN_FAILURE",
};
